config/routes.rb
Rails.application.routes.draw do
  resources :copropietarios
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'copropietario' => 'copropietarios#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/copropietario.rb
class Copropietario < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception
end

app/controllers/copropietarios_controller.rb
class CopropietariosController < ApplicationController
  before_action :set_copropietario, only: [:show, :edit, :update, :destroy]

  # GET /copropietarios
  # GET /copropietarios.json
  def index
    @copropietarios = Copropietario.all
  end

  # GET /copropietarios/1
  # GET /copropietarios/1.json
  def show
  end

  # GET /copropietarios/new
  def new
    @copropietario = Copropietario.new
  end

  # GET /copropietarios/1/edit
  def edit
  end

  # POST /copropietarios
  # POST /copropietarios.json
  def create
    @copropietario = Copropietario.new(copropietario_params)

    respond_to do |format|
      if @copropietario.save
        format.html { redirect_to @copropietario, notice: 'Copropietario was successfully created.' }
        format.json { render :show, status: :created, location: @copropietario }
      else
        format.html { render :new }
        format.json { render json: @copropietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /copropietarios/1
  # PATCH/PUT /copropietarios/1.json
  def update
    respond_to do |format|
      if @copropietario.update(copropietario_params)
        format.html { redirect_to @copropietario, notice: 'Copropietario was successfully updated.' }
        format.json { render :show, status: :ok, location: @copropietario }
      else
        format.html { render :edit }
        format.json { render json: @copropietario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copropietarios/1
  # DELETE /copropietarios/1.json
  def destroy
    @copropietario.destroy
    respond_to do |format|
      format.html { redirect_to copropietarios_url, notice: 'Copropietario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copropietario
      @copropietario = Copropietario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copropietario_params
      params.require(:copropietario).permit(:id_copropietario, :nombres, :cedula, :fecha_nacimiento, :actividad, :direccion, :telefono, :celular, :mail, :id_edificio, :id_departamento)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/copropietarios_helper.rb
module CopropietariosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/copropietarios/_form.html.erb
<%= form_with(model: copropietario, local: true) do |form| %>
  <% if copropietario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(copropietario.errors.count, "error") %> prohibited this copropietario from being saved:</h2>

      <ul>
        <% copropietario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id_copropietario %>
    <%= form.text_field :id_copropietario %>
  </div>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :cedula %>
    <%= form.text_field :cedula %>
  </div>

  <div class="field">
    <%= form.label :fecha_nacimiento %>
    <%= form.date_select :fecha_nacimiento %>
  </div>

  <div class="field">
    <%= form.label :actividad %>
    <%= form.text_field :actividad %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :celular %>
    <%= form.text_field :celular %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>

  <div class="field">
    <%= form.label :id_edificio %>
    <%= form.text_field :id_edificio %>
  </div>

  <div class="field">
    <%= form.label :id_departamento %>
    <%= form.text_field :id_departamento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/copropietarios/edit.html.erb
<h1>Editing Copropietario</h1>

<%= render 'form', copropietario: @copropietario %>

<%= link_to 'Show', @copropietario %> |
<%= link_to 'Back', copropietarios_path %>

app/views/copropietarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Copropietarios</h1>

<table class="table">
  <thead class="thead-dark">
    <tr class="">
      <th scope="col">#</th>
      <th scope="col">Id Copropietario</th>
      <th scope="col">Nombres</th>
      <th scope="col">Cedula</th>
      <th scope="col">Fecha de Nacimiento</th>
      <th scope="col">Actividad</th>
      <th scope="col">Direccion</th>
      <th scope="col">Telefono</th>
      <th scope="col">Celular</th>
      <th scope="col">Mail</th>
      <th scope="col">Id_Edificio</th>
      <th scope="col">Id_Departamento</th>
      <th scope="col" colspan="3">Acciones </th>
    </tr>
  </thead>

  <tbody>
    <% @copropietarios.each do |copropietario| %>
      <tr>
        <th scope="row"><%=copropietario.id %></th>
        <td><%= copropietario.id_copropietario %></td>
        <td><%= copropietario.nombres %></td>
        <td><%= copropietario.cedula %></td>
        <td><%= copropietario.fecha_nacimiento %></td>
        <td><%= copropietario.actividad %></td>
        <td><%= copropietario.direccion %></td>
        <td><%= copropietario.telefono %></td>
        <td><%= copropietario.celular %></td>
        <td><%= copropietario.mail %></td>
        <td><%= copropietario.id_edificio %></td>
        <td><%= copropietario.id_departamento %></td>
        <td><%= link_to 'Show', copropietario %></td>
        <td><%= link_to 'Edit', edit_copropietario_path(copropietario) %></td>
        <td><%= link_to 'Destroy', copropietario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Copropietario', new_copropietario_path %>

app/views/copropietarios/new.html.erb
<h1>New Copropietario</h1>

<%= render 'form', copropietario: @copropietario %>

<%= link_to 'Back', copropietarios_path %>

app/views/copropietarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id copropietario:</strong>
  <%= @copropietario.id_copropietario %>
</p>

<p>
  <strong>Nombres:</strong>
  <%= @copropietario.nombres %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @copropietario.cedula %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @copropietario.fecha_nacimiento %>
</p>

<p>
  <strong>Actividad:</strong>
  <%= @copropietario.actividad %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @copropietario.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @copropietario.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @copropietario.celular %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @copropietario.mail %>
</p>

<p>
  <strong>Id edificio:</strong>
  <%= @copropietario.id_edificio %>
</p>

<p>
  <strong>Id departamento:</strong>
  <%= @copropietario.id_departamento %>
</p>

<%= link_to 'Edit', edit_copropietario_path(@copropietario) %> |
<%= link_to 'Back', copropietarios_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Control de Condominios", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Mi cuenta", edit_user_registration_path %></li>
          <li><%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Regístrate", new_user_registration_path %></li>
          <li><%= link_to "Iniciar sesión", new_user_session_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Condominios</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render 'layouts/header' %>

  <body>
    <div class="container-fluid">

        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> fade in">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        <% end %>

        <%= yield %>

    </div>
  </body>

</html>

app/views/pages/about.html.erb
<h1>¿Quién soy?</h1>
<p>Es una App creada por Cesar Mancheno Vargas, para el eficiente Manejo de Condominios¡</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h2>Bienvenidos a Control de Condominios</h2>
  <p>Para tener administracion eficiente de Edificios</p>
   <% if !user_signed_in? %>
     <p>
       <%= link_to "Iniciar sesión", new_user_session_path, class: "btn btn-default btn-lg" %>
       <%= link_to "Regístrate", new_user_registration_path, class: "btn btn-primary btn-lg" %>
     </p>
    <% end %>
</div>

<div class="">
  <% if user_signed_in? %>
    <div class="container-fluid">
      <div class="row">
        <div class="col">
          <%= link_to "Copropietarios", copropietarios_path, class: "btn btn-default btn-lg" %>
        </div>
        <div class="col order-1">
          <%= link_to "Inquilinos", copropietarios_path, class: "btn btn-default btn-lg" %>
        </div>
        <div class="col order-1">
          <%= link_to "Edificios", copropietarios_path, class: "btn btn-default btn-lg" %>
        </div>
        <div class="col order-1">
          <%= link_to "Departamentos", copropietarios_path, class: "btn btn-default btn-lg" %>
        </div>
      </div>
    </div>
  <% end %>
</div>